### ISSUE TITLE
reading ascii json file in python

### ISSUE THREAD

**Issue by nikhil003** [jacobwilliams/json-fortran#115] opened 2015-06-29 17:55 UTC
Hi, I used json-fortran to make a simple json file in ascii coding and now i am trying to read it in python. I am new to whole json thing and its usage in python. I was wondering if you guys can help in the right way of doing things.

this is how my json file looks like

{
  "wind": {
    "data": [
      0.1315439868029756E-1,
      -0.9139016210606232E-1,
      -0.5994115391400573E-2,
      0.5139171464019829E-2,
      -0.3217021608035014E-1,
      0.3420904476010936E-1,
      -0.5603734322336748E-2,
      0.4198970987766211E-1,
      -0.8014594416755605E-1,
      -0.401277499140136E-3,
      -0.6231748067648588E-2,
      0.5025478310972475E-1,
      -0.1017393907520015E-1,
      0.7328809386698122E-2,
      0.8651108835837368E-1,
      0.1423462151077473E-2,
      -0.4802597667398823E-1,
      -0.1234297411746424E+0,
      0.1802706487197827E-1,
      0.4596847031212745E-1,
      -0.6266251225726563E-2,
      -0.7302086138704866E-1,
      0.3525357659986639
      ......
    ],
    "shape": [
      100,
      100
    ],
    "dtype": "float"
  }
}

appreciate any help. i know i should be asking someone in python forum but i thought why not try here.

**Comment by zbeekman** [comment] 2015-06-29 17:58
what have you tried?

**Comment by zbeekman** [comment] 2015-06-29 18:00
also go ahead and close this issue please since it has nothing to do with json-fortran, we can carry on the conversation here or somewhere else even if the issue is closed.

**Comment by zbeekman** [comment] 2015-06-29 18:02
I don’t have much experience with python, but take a look here: http://stackoverflow.com/questions/2835559/parsing-values-from-a-json-file-in-python

**Comment by jacobwilliams** [comment] 2015-06-29 18:03
See also: http://stackoverflow.com/questions/6578986/how-to-convert-json-data-into-a-python-object/15882054#15882054

**Closed by jacobwilliams** 2015-06-29 18:03 UTC
