### ISSUE TITLE
A way to pass GFortran's neutral integer edit descriptor(I0) bug

### ISSUE THREAD

**Issue by demiryavuz** [jacobwilliams/json-fortran#285] opened 2017-06-12 20:14 UTC
I am wondering if GFortran compiles with 

Instead of 
`read(str,'(I0)') ival`

in the json string utilities, have you ever tried the placeholder in format statements. 

`read(str, '(I<ndigits>)') ival `

where

`ndigits`
is an integer? Thank you.

**Comment by demiryavuz** [comment] 2017-06-12 20:16
Ops. There was the variable ndigits inside the brackets  that is cleared in the first read statement. Sorry. A novice in these platforms.

**Comment by zbeekman** [comment] 2017-06-12 20:55
Hi @demiryavuz, if you are satisfied, please close this issue, otherwise, please clarify what you are asking about. Thanks!

**Comment by demiryavuz** [comment] 2017-06-12 23:41
Ok. Sorry, wrote the issue at waffle, just saw the wysiwyg editor here on github.I have updated it.

**Comment by zbeekman** [comment] 2017-06-13 12:26
Still a little bit unclear to me what you are asking... Are you saying you want to change JSON-Fortran's default integer output to fixed length?

**Comment by demiryavuz** [comment] 2017-06-13 19:16
OK. My bad. Let me try last time and close the issue. I was looking at json_string_utilities.f90 and in the routine string_to_integer between the lines 115 and 137, I saw a comment next to the statement 
`write(digits,'(I0)') ndigits` 
and the comment is 
!gfortran will have a runtime error with * edit descriptor here
! gfortran bug: '*' edit descriptor for ISO_10646 strings does bad stuff.
I don't have gfortran compiler  and in the statement above number of digits is written to a string and then used in the statement 
`read(str,'(I'//trim(digits)//')',iostat=ierr) ival `
My question comes into play here? Once you know the number of digits in an integer, (and it is stored in a variable like ndigits) compilers I have used so far allowed 
 `read(str,'(I<ndigits>)',iostat=ierr) ival `
where brackets can be used. Have you ever tried this in GFrotran? This placeholder is very handy in fact. You can use anywhere possible in the format statements.

**Comment by zbeekman** [comment] 2017-06-13 21:48
OK, just to make sure I understand you: This question is about GFortran and __*NOT*__ actually about JSON-Fortran at all, correct?

A bit off-topic, but OK. Unless I am misunderstanding you, as far as I know, `read(str,'(I<ndigits>)',iostat=ierr) ival` is not valid Fortran, since I don't think it is in the standard. If this is the case, then it is a compiler extension, and really should be avoided if your aim is to write portable code. I can confirm that GFortran-7 doesn't like this:

foo.f90:
```Fortran
program main
  implicit none
  integer :: ierr, ival, ndigits
  character(len=20) :: str

  ndigits=5
  ival=31415
  read(str,'(I<ndigits>)',iostat=ierr) ival
  print*, 'First 5 digist of pi are: ', str

end program main
```

```shell
gfortran-7 foo.f90
foo.f90:8:14:

   read(str,'(I<ndigits>)',iostat=ierr) ival
              1
Error: Nonnegative width required in format string at (1)
```

If you really mean something like `read(str,'(I5)',iostat=ierr) ival`, then yes, of course GFortran supports that. Your last comment still isn't particularly clear to me. Particularly the part where you attempt to explain your question again: 

> My question comes into play here? Once you know the number of digits in an integer, (and it is stored in a variable like ndigits) compilers I have used so far allowed
read(str,'(I<ndigits>)',iostat=ierr) ival
where brackets can be used. Have you ever tried this in GFrotran?

Fortunately, the first paragraph of your most recent comment at least gave me some context to guess at what you are asking.

**Comment by demiryavuz** [comment] 2017-06-13 23:17
OK. Thank you. That must be an extension then. That lived in Compact and Intel compilers until now I guess. 

Looks like it is better to stick into string concatenation for portability.

**Closed** 2017-06-13 23:17 UTC
